[tool.black]
line-length = 120

[tool.isort]
py_version=311
sections="FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
import_heading_stdlib="standard libraries"
import_heading_thirdparty="third party libraries"

[tool.ruff]
line-length = 120
